name: CI/CD Pipeline

on:
  push:
    # TODO: fix the triggers. Also have a separate
    # workflow for PR.
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Plan and Apply
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.11.4

    - name: Terraform Init
      run: terraform init
      working-directory: ${{ github.event.repository.name }}/environments/staging

    - name: Terraform Plan
      run: terraform plan
      working-directory: ${{ github.event.repository.name }}/environments/staging

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve
      working-directory: ${{ github.event.repository.name }}/environments/staging