# Ref: https://github.com/hashicorp/setup-terraform/tree/v2/
#
# This workflow is triggered on pull requests to the dev branch.
# It runs Terraform commands to validate and plan changes, and comments the results back to the PR.
# It uses a matrix strategy to run the same steps for both staging and production environments.
# The workflow also includes a step to comment on the PR with the results of the Terraform commands.
# The comment includes the outcomes of formatting, initialization, validation, and planning.
# The comment is updated if it already exists, or created if it doesn't.
name: CI Pipeline

on:
  pull_request:
    branches:
      - dev

jobs:
  terraform:
    name: validate and plan
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    strategy:
      matrix:
        # environment: [staging, production]
        environment: [staging]
        workload_identity_provider: [
            # staging
            'projects/12313737332/locations/global/workloadIdentityPools/infrastructure-pool/providers/infrastructure-provider',
            # production
            'projects/<TBD>/locations/global/workloadIdentityPools/infrastructure-pool/providers/infrastructure-provider'
        ]
        exclude:
          - environment: staging
            workload_identity_provider: 'projects/<TBD>/locations/global/workloadIdentityPools/infrastructure-pool/providers/infrastructure-provider'
          - environment: production
            workload_identity_provider: 'projects/12313737332/locations/global/workloadIdentityPools/infrastructure-pool/providers/infrastructure-provider'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - id: auth
        name: Setup Google Cloud credentials for ${{ matrix.environment }} 
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: dr-copilot-${{ matrix.environment }}
          workload_identity_provider: ${{ matrix.workload_identity_provider }}
          export_environment_variables: true
          create_credentials_file: true
          cleanup_credentials: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
            terraform_version: 1.11.4
      
      - name: ${{ matrix.environment }} terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: false
        working-directory: environments/${{ matrix.environment }}

      - name: ${{ matrix.environment }} terraform init
        id: init
        run: terraform init
        working-directory: environments/${{ matrix.environment }}

      - name: ${{ matrix.environment }} terraform validate
        id: validate
        run: terraform validate -no-color
        working-directory: environments/${{ matrix.environment }}
      
      - name: ${{ matrix.environment }} terraform test
        id: test
        run: terraform test
        working-directory: environments/${{ matrix.environment }}

      - name: ${{ matrix.environment }} terraform plan
        id: plan
        run: terraform plan -out .planfile
        working-directory: environments/${{ matrix.environment }}
        continue-on-error: true
    
      - name: Post PR comment
        uses: borchero/terraform-plan-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          planfile: .planfile
          working-directory: environments/${{ matrix.environment }}